### ISSUE TITLE
ER Modell (Database layout)

### ISSUE THREAD

**Issue by oliverpool** [packmas13/registration#1]
Vorschlag von @ackxolotl 23.01.2020:

> ![image](https://user-images.githubusercontent.com/3864879/73087013-0cfa3580-3ed2-11ea-87d8-cd1f68109208.png)
> Hier nochmal ne aktuellere Version ... ich hab mal alle Felder mit nem Fragezeichen markiert, die aus meiner Sicht diskutabel sind, ob wir die wirklich brauchen
> Muss z. B. sowas wie Medikamente bei "uns" gespeichert werden? Reicht das nicht, wenn die Information der Leiter/StaVo hat?
> Brauchen wir das Geschlecht der Teilnehmer?
> Das mit der NaMi-Nummer is z. B. auch so ne Sache, afaik besteht Versicherungsschutz ja ab dem Moment des Eingangs der Anmeldung beim StaVo und nicht dadurch, dass jemand in der NaMi eingetragen is ... wenn wir erzwingen, dass nur Leute im Tool angemeldet werden können, die in der NaMi stehen, gibt's halt vielleicht Teilnehmer auf dem Lager, die nicht angemeldet sind ... weil der StaVo die NaMi-Anmeldung verpennt hat z. B.

Meine Überlegungen dazu:
- ScoutTroop statt ScoutGroup

- NAMI: ich glaube nicht, dass viele "frisch-angemeldete Pfadinder" spontan an einem DioLa teilnehmen (ie, noch keine NAMI-Nummer). Ich würde es Pflichtfeld lassen (und evtl hacken, wenn es nötig ist - mit 999XXX Nummern, bis die richtige Nummer kommt zB). Es versichert auch, dass niemand mehrmals angemeldet sind.

- phone: war nur für Helfer gedacht. Hängt davon ab, ob ein getrenntes Helfertool verwendet wird.

- medication: ja, wäre besser, wenn es nicht da wäre. Aber die Lagerleitung/Sani-Leute brauchen sicherlich diese Info irgendwie

- status: es wurde für Abmeldungen verwendet. Vllt lieber einen Feld "deleted_at" (null = angemeldet, Datum = es wurde an dem Zeitpunk abgemeldet)
=> Alle Queries sollte nur deleted_at<>NULL nehmen (außer für die Abrechnung)

- payment: würde ich löschen und dafür eine neue Tabelle "Discounts" machen (mit "participant", "amount", "created_at", "comment").
Alle Leute müssen X (Lager Beitrag) zahlen - Summe von den Discounts (Helfer hat zB Y € Discount / spät anmeldung ein negatives Discount / Abmeldung kann auch einen Discount geben usw)

- has_paid: löschen und dafür eine Tabelle "Payments" (many to one ScoutTroop) (mit "ScoutTroop", "amount", "created_at", "comment")

**Comment by ackxolotl** [comment]
![last](https://user-images.githubusercontent.com/39318299/73135265-70a27100-4040-11ea-89e6-7a21358d22fe.png)

Langsam nimmt das Modell Formen an :) Ich hab noch ein paar Felder gelöscht, vor allem was Helfermanagement angeht. Falls das auch über die Teilnehmerregistrierung laufen soll, würde ich dafür eine eigene `Staff`-Tabelle machen (z. B. mit einem Feld für die Telefonnummer) und `Role`s. Das können wir aber zu einem späteren Zeitpunkt machen.

**Comment by oliverpool** [comment]
## Über `participants`:
- Braucht man `email`? (war bei Einfach 13 nicht im DB)
- `diet` braucht wahrscheinlich 2 Tabelle dazu (pivot + data)
  data: `Vegetarier`, `Vegan`, `Glutenfrei`, `Laktosefrei`...
  Es muss auch einigermaßen personalisierbar sein (für Sonderallergie, die man im Voraus nicht denken kann) Vllt einfacher erlauben, data hinzufügen in der Tabelle.
- Vllt lieber `unregistered_at` statt `deregistered_at` (https://english.stackexchange.com/a/40095)

Allgemein sieht es gut aus, und kann wahrscheinlich schon implementiert werden.

**Comment by ackxolotl** [comment]
- `email` hätte ich reingemacht um Info-Mails an Teilnehmer verschicken zu können, z. B. von Stufenreferenten, Lagerleitung, Büro. Können ja die Lagerleitung nochmal fragen, ob das sinnvoll ist?
- Guter Punkt mit `diet`. Dachte ursprünglich an ein Freitextfeld, aber so ist das vielleicht besser.
- Hm, also laut den StackExchange-Antworten passt aber doch `deregister` besser. Geht ja um den Zeitpunkt der Abmeldung, Übergang von Zustand `registered` zu `unregistered` ... also `deregistered_at` :D

**Comment by ackxolotl** [comment]
![last](https://user-images.githubusercontent.com/39318299/73142378-0b756c80-408e-11ea-94ea-666e7dd622b5.png)

Aktualisierte Version. Hab die One-to-Many+Many-to-One-Beziehungen durch Many-to-Many-Beziehungen ersetzt. Hoffentlich stimmt noch alles?

**Comment by oliverpool** [comment]
Von mir aus, passt alles (`email` könnte man dann im `Staff` packen, wenn es nur für bestimmte Leute gebraucht ist)

**Comment by StefanKuppelwieser** [comment]
> ![last](https://user-images.githubusercontent.com/39318299/73135265-70a27100-4040-11ea-89e6-7a21358d22fe.png)
> 
> Langsam nimmt das Modell Formen an :) Ich hab noch ein paar Felder gelöscht, vor allem was Helfermanagement angeht. Falls das auch über die Teilnehmerregistrierung laufen soll, würde ich dafür eine eigene `Staff`-Tabelle machen (z. B. mit einem Feld für die Telefonnummer) und `Role`s. Das können wir aber zu einem späteren Zeitpunkt machen.
> 
> Ein Edgecase ist mir noch eingefallen: Stellt euch vor, jemand ist Rover und Wölflingsleiter. Das können wir aktuell nicht abbilden, weil man aktuell nur Leiter einer Stufe oder Teilnehmer einer Stufe sein kann. Sollen wir das noch ändern?

Das mit dem Edgecase ist ein guter Hinweis. Kann es aber auch unnötig kompliziert machen. An sich bin ich dafür dass ein Leiter 0..1Stufe haben kann. Aber ich weiß auch das es Stämme gibt bei denen die Stufen doppelt besetzt sein müssen da ansonsten Stufe b keine Leiter hat.

Vorschlag 1: ein Leiter hat 0..1 Stufe haben
Vorschlag 2: ein Leiter kann 0..* Stufen haben wobei es 1 primär-stufe gibt 

Kann man eine Abfrage einbauen , dass jede angegebene Stufe mindestens 1 Leiter zugeordnet sein muss.

**Comment by StefanKuppelwieser** [comment]
> * `email` hätte ich reingemacht um Info-Mails an Teilnehmer verschicken zu können, z. B. von Stufenreferenten, Lagerleitung, Büro. Können ja die Lagerleitung nochmal fragen, ob das sinnvoll ist?
> * Guter Punkt mit `diet`. Dachte ursprünglich an ein Freitextfeld, aber so ist das vielleicht besser.
> * Hm, also laut den StackExchange-Antworten passt aber doch `deregister` besser. Geht ja um den Zeitpunkt der Abmeldung, Übergang von Zustand `registered` zu `unregistered` ... also `deregistered_at` :D

Die E-Mail kann man ja optional lassen oder ? Ansonsten stimme ich zu mit dem verteilen von News 

Beim staff kann man ja  die Mail verpflichtend machen ?

**Comment by StefanKuppelwieser** [comment]
Zu der Tabelle Payments:

- sollen folgende Attribute noch hinzugefügt werden ? Payed_at, paid_amount
- soll es auch eine Info geben wenn es vollständig abgerechnet ist ?
- soll es ein value geben der angibt wie viel nachgezahlt werden muss bzw. Gut geschrieben wird ?

**Comment by StefanKuppelwieser** [comment]
Bei der Tabelle attendance:

- vielleicht start_date und end_date ? 


Tabelle troop

- vielleicht noch eine Tabelle mit ner 1..n Beziehung hinzufügen , die die Bezirke zu den Troops zuordnet ? 


Das wären meine Gedanken 😊 schaut aber bisher gut aus. Danke für die Mühe 👍

**Comment by oliverpool** [comment]
> Vorschlag 1: ein Leiter hat 0..1 Stufe haben
> Vorschlag 2: ein Leiter kann 0..* Stufen haben wobei es 1 primär-stufe gibt

Irgendwie finde ich das alles ziemlich kompliziert, und bin nicht sicher, wofür es verwendet sein solltest.

Wenn man wissen will, wie viele Leute es pro Dorf gibt (Wö-Dorf zB), dann reicht eine Stufe (ein Leiter kann nicht in 2 Dörfer gleichzeitig sein...).

Bevor wir da zu viel Komplexität einbauen, wird ich es einfach lassen und die Lagerleitung nachfragen, was sie damit genau vor haben.

> Beim staff kann man ja die Mail verpflichtend machen ?

Stimmt, in der [`Staff`](https://github.com/packmas13/registration/issues/1#issuecomment-578546973) Tabelle macht es total Sinn!

> soll es auch eine Info geben wenn es vollständig abgerechnet ist ?
> soll es ein value geben der angibt wie viel nachgezahlt werden muss bzw. Gut geschrieben wird ?

Kann man direkt rechnen, mit was schon in der Datenbank ist (`Ausstehend` = `Anzahl von Teilnehmer`*`Preis pro Teilnehmer` - `Discounts` - `Payments`)

> vielleicht start_date und end_date ?

So (mit nur einen `date`) ist es flexibler (falls Leute am beide Wochenende kommen, aber nicht unter der Woche zB).

> vielleicht noch eine Tabelle mit ner 1..n Beziehung hinzufügen , die die Bezirke zu den Troops zuordnet ?

Mit der DPSG-Nummer kann man es auch machen (Alle Stämme, die mit 1312 anfangen, gehören zum Bezirk 131200)

**Comment by StefanKuppelwieser** [comment]
> > Vorschlag 1: ein Leiter hat 0..1 Stufe haben
> > Vorschlag 2: ein Leiter kann 0..* Stufen haben wobei es 1 primär-stufe gibt
> 
> Irgendwie finde ich das alles ziemlich kompliziert, und bin nicht sicher, wofür es verwendet sein solltest.
> 
> Wenn man wissen will, wie viele Leute es pro Dorf gibt (Wö-Dorf zB), dann reicht eine Stufe (ein Leiter kann nicht in 2 Dörfer gleichzeitig sein...).
> 
> Bevor wir da zu viel Komplexität einbauen, wird ich es einfach lassen und die Lagerleitung nachfragen, was sie damit genau vor haben.
> 
Ich kann das gerne in die nächste Ältestenratrunde mitnehmen. Soweit ich weiß wird das für die Planung des Programms verwendet. Stufenprogramm, etc.


> > Beim staff kann man ja die Mail verpflichtend machen ?
> 
> Stimmt, in der [`Staff`](https://github.com/packmas13/registration/issues/1#issuecomment-578546973) Tabelle macht es total Sinn!
> 
> > soll es auch eine Info geben wenn es vollständig abgerechnet ist ?
> > soll es ein value geben der angibt wie viel nachgezahlt werden muss bzw. Gut geschrieben wird ?
> 
> Kann man direkt rechnen, mit was schon in der Datenbank ist (`Ausstehend` = `Anzahl von Teilnehmer`*`Preis pro Teilnehmer` - `Discounts` - `Payments`)
> 
> > vielleicht start_date und end_date ?
> 
> So (mit nur einen `date`) ist es flexibler (falls Leute am beide Wochenende kommen, aber nicht unter der Woche zB).

Soll dann date ein integer sein der die Anzahl der Nächte beschreibt? Mich würde als Benutzer interessieren viel viele bspw. an dern Vortagen zum Aufbau sowie visa versa

> 
> > vielleicht noch eine Tabelle mit ner 1..n Beziehung hinzufügen , die die Bezirke zu den Troops zuordnet ?
> 
> Mit der DPSG-Nummer kann man es auch machen (Alle Stämme, die mit 1312 anfangen, gehören zum Bezirk 131200)

Gute Idee :)

**Comment by ackxolotl** [comment]
> > Vorschlag 1: ein Leiter hat 0..1 Stufe haben
> > Vorschlag 2: ein Leiter kann 0..* Stufen haben wobei es 1 primär-stufe gibt
> 
> Irgendwie finde ich das alles ziemlich kompliziert, und bin nicht sicher, wofür es verwendet sein solltest.

Ja, der Punkt mit "jeder kann nur an einem Programmpunkt teilnehmen" war gut. Das Leiterfeld ist jetzt einfach `Boolean`, wenn die Lagerleitung es komplizierter will, können wir das ja wieder ändern ;)

> Stimmt, in der [`Staff`](https://github.com/packmas13/registration/issues/1#issuecomment-578546973) Tabelle macht es total Sinn!

Wie gesagt, bei Teilnehmern macht es für Infos von der Lagerleitung, dem Lagerradio, Stufen, ..., sehr wohl Sinn. Ich würde mir den Kanal offen halten.

> Kann man direkt rechnen, mit was schon in der Datenbank ist (`Ausstehend` = `Anzahl von Teilnehmer`*`Preis pro Teilnehmer` - `Discounts` - `Payments`)

Genau

> So (mit nur einen `date`) ist es flexibler (falls Leute am beide Wochenende kommen, aber nicht unter der Woche zB).

Seh ich auch so.

> Mit der DPSG-Nummer kann man es auch machen (Alle Stämme, die mit 1312 anfangen, gehören zum Bezirk 131200)

So würde ich das auch machen.

**Comment by ackxolotl** [comment]
![last](https://user-images.githubusercontent.com/39318299/73315356-27b10f00-4230-11ea-82e3-503bfde6775f.png)

Hier der letzte Stand des Modells, wie es mit Commit 51e4345e1e056b39f1bb939cbf0d3e579a3acd56 implementiert sein sollte (abgesehen von den fehlenden Tabellen `Staff` und `Role`, und den halbautomatisch generierten Tabellen `User` und `Group`).

Wichtig für die weitere Implementierung sind natürlich noch die Rechte, die einzelne Nutzer und Gruppen bekommen sollen. Die können wir aber hoffentlich mit [Djangos Permissions](https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#custom-permissions) abbilden.

**Comment by ackxolotl** [comment]
Ich schließe mal den Issue, da die Diskussion an dieser Stelle denk ich vorerst abgeschlossen ist. Wir können ihn ja zu gegebenem Zeitpunkt wieder aufmachen.
