### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by ackxolotl** [packmas13/registration#11]
This issue is an attempt to define all required views (excluding those that do not provide a visible page, e.g. logout).

## `/`

* should redirect to `account/login/` if no `User` is currently logged in
* should otherwise display `...` (maybe some fancy dashboard with graphs)?
* menu contains references to
  * `account/logout/`
  * `participant/`
  * `...`

## `account/login/`

* contains a form to log in containing `email` address and `password` and
* a reset button to reset a `User`'s password

## `account/reset/`

* contains a form to reset a `User`s password
* send a password reset link via email to the `User`

## `participant/`

* contains a table which lists all `Participant`s which the active `User` can access
* table can be ordered by various fields, e.g. troop, firstname, lastname, birthday, ...
* hyperlinks to
  * `participant/add/`
  * `participant/batch_add/`
  * `...`

## `participant/add/`

* contains a form listing all fields to create a single `Participant`
* `Troop` is a dropdown field containing all `Troop`s the active `User` can manage

## `participant/batch_add/`

* contains a table like view where NaMi accounts can be selected to be imported as `Participant`s

## `payment/`

* contains two tables which lists all `Payment`s and `Discount`s which the active `User` can access
* tables can be ordered by various fields
* hyperlinks to
  * `...`

## `...`

**Comment by oliverpool** [comment]
Instead of doing it "horizontally" (one issue for all the views, one issue for all DB calls, one issue for all email etc) I would rather have "vertical" issues:
- one regarding the import (with command and email)
- one for the user management (login, logout, password views and reset email)
- one for the participant registration
- ...

This is what I tried to picture with https://github.com/packmas13/registration/issues/10 (feel free to edit it).

This approach is much easier to "sell" to outsiders, because we can present a specific piece of functionality end-to-end.

**Comment by ackxolotl** [comment]
My idea behind this issue was to get a complete picture of the website like a drawn sketch of the pages in text form so that we know

a) what views there will be and – besides functionality ­–
b) what visual elements the views should contain

My feeling with #10 was that it is a functional description of the website, illustrating various operations a user might carry out. I am missing a more detailed description of the views.

**Comment by oliverpool** [comment]
> My feeling with #10 was that it is a functional description of the website, illustrating various operations a user might carry out. I am missing a more detailed description of the views.

I would rather have #10 better detailed (which information must be provided in each step).

The actual views needed will become clear one we write the tests to complete the different steps :-)

**Comment by ackxolotl** [comment]
Ok, so let's try it with #10. I'll close this issue.
