### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by 6543** [packmas13/registration#5]
So we will have 2 main translations ... the English and the German one ...

is there a need for more?
if so I'll integrate a translation tool (for non programmers who can translate strings ... [thinking of crowdin.com])

**Comment by ackxolotl** [comment]
There was a discussion whether translations in general are over-the-top for this project. Imho, the main point of having a German translation is clean code written in English without German terminology in it. Thus, I think English and German will be enough.

**Comment by 6543** [comment]
> clean code written in English

this is good for all other devs who maby will look at this :)

I'll close this for now ... if somebody like to have a translation in some language ... just comment below in this issue ...
