### ISSUE TITLE
Licence Selection

### ISSUE THREAD

**Issue by 6543** [packmas13/registration#6]
I think we all agree this should be open source ... but WITCH licence we like to use :D

**Comment by ackxolotl** [comment]
I'd prefer AGPL, although a 🧙-license would also be fun (scnr) ;-)

**Comment by 6543** [comment]
https://choosealicense.com/licenses  I use GPL3+ and MIT ...

**Comment by 6543** [comment]
MIT if i dont think a company could take over my code base and write a product ontop of it (if not intendet)
and GPL3+ if its a project witch can be used and is to compete otherwyse ... so if some company is using it it's more likly changes/fix will be contributed back ... <- of cource AGPL goes future ...

**Comment by 6543** [comment]
# Vote
 * :+1: MIT
* :laughing: GPL3+
* :tada: AGPL

**Comment by oliverpool** [comment]
We probably need to add some exception regarding logos and graphics that are property of others (like the dpsg logo).

**Comment by ackxolotl** [comment]
So, I guess MIT won the vote. Feel free to add the license ;)
